const calendarTrackerTypes = {
  ADD_NEW_CALENDAR: "ADD_NEW_CALENDAR",
  ADD_NEW_DAY: "ADD_NEW_DAY",

  FETCH_CALENDARS_START: "FETCH_CALENDARS_START",
  SET_CALENDARS: "SET_CALENDARS",

  FETCH_USER_CALENDAR: "FETCH_USER_CALENDAR",
  SET_USER_CALENDAR: "SET_USER_CALENDAR",
  // SET_DAY: "SET_DAY",
  // DELETE_DAY_START: "DELETE_DAY_START",
};

export default calendarTrackerTypes;
