const weekTrainingTypes = {
  ADD_NEW_TRAINING_SCHEDULE: "ADD_NEW_TRAINING_SCHEDULE",

  FETCH_TRAINING_SCHEDULES_START: "FETCH_TRAINING_SCHEDULES_START",
  SET_TRAINING_SCHEDULES: "SET_TRAINING_SCHEDULES",

  FETCH_USER_TRAINING_SCHEDULE: "FETCH_USER_TRAINING_SCHEDULE",
  SET_USER_TRAINING_SCHEDULE: "SET_USER_TRAINING_SCHEDULE",

  ADD_NEW_TRAINING_WEEK_START: "ADD_NEW_TRAINING_WEEK_START",
};

export default weekTrainingTypes;
