const weekTrainingTypes = {
  ADD_NEW_TRAINING_SCHEDULE: "ADD_NEW_TRAINING_SCHEDULE",

  FETCH_TRAINING_SCHEDULE_START: "FETCH_TRAINING_SCHEDULE_START",

  SET_TRAINING_SCHEDULES: "SET_TRAINING_SCHEDULES",
};

export default weekTrainingTypes;
